name: ktlint

on: 
  push:
    paths:
    - "**/*.kt"
    - ".github/workflows/ktlint.yml"
    branches:
      - master
      - development

  pull_request:
    paths:
      - "**/*.kt"
      - ".github/workflows/ktlint.yml"
    branches:
      - master
      - development
  jobs:
    ktlint:
      runs-on: ubuntu-latest

      steps:
        - name: "checkout"
           uses: actions/checkout@v2

        - name: "ktlint"
           uses: "vroy/gha-kotlin-linter@v1"
